### ISSUE TITLE
Typescript error: TS2307 due to imports from `src` in type declarations

### ISSUE THREAD

**Issue by Averethel** [chakra-ui/chakra-ui#6021]
### Description

`tsc` raises the type error TS2307 with following issues:
 - Cannot find module '@chakra-ui/descendant/src/use-descendant' or its corresponding type declarations
 - Cannot find module '@chakra-ui/toast/src' or its corresponding type declarations
 - Cannot find module '@chakra-ui/theme/src/components' or its corresponding type declarations

 when compiling the project.

Affected packages:

- @chakra-ui/accordion
- @chakra-ui/menu
- @chakra-ui/pin-input
- @chakra-ui/react
- @chakra-ui/tabs

### Link to Reproduction

x

### Steps to reproduce

Try to compile a typescript project (exact dependency versions and tsconfig provided below).

### Chakra UI Version

2.0.0

### Browser

x

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

tsconfig:
```json
{
  "compilerOptions": {
    "strict": true,
    "jsx": "react",
    "module": "esnext",
    "declaration": true,
    "declarationDir": "types",
    "sourceMap": true,
    "outDir": "dist",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "esModuleInterop": true
  },
  "exclude": ["dist", "node_modules"],
  "include": ["src"]
}
```

related dependencies:
```
  "typescript": "4.6.4",
  "@chakra-ui/react": "2.0.0",
  "@chakra-ui/system": "2.0.0",
  "@chakra-ui/theme": "2.0.0",
  "@chakra-ui/theme-tools": "2.0.0",
  "@emotion/react": "11.9.0",
  "@emotion/styled": "11.8.1",
  "framer-motion": "6.3.3"
```

tsc output:
```
node_modules/@chakra-ui/accordion/dist/declarations/src/use-accordion.d.ts:7:25 - error TS2307: Cannot find module '@chakra-ui/descendant/src/use-descendant' or its corresponding type declarations.

7     descendants: import("@chakra-ui/descendant/src/use-descendant").UseDescendantsReturn;
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@chakra-ui/menu/dist/declarations/src/use-menu.d.ts:9:25 - error TS2307: Cannot find module '@chakra-ui/descendant/src/use-descendant' or its corresponding type declarations.

9     descendants: import("@chakra-ui/descendant/src/use-descendant").UseDescendantsReturn;
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@chakra-ui/pin-input/dist/declarations/src/use-pin-input.d.ts:6:25 - error TS2307: Cannot find module '@chakra-ui/descendant/src/use-descendant' or its corresponding type declarations.

6     descendants: import("@chakra-ui/descendant/src/use-descendant").UseDescendantsReturn;
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@chakra-ui/react/dist/declarations/src/chakra-provider.d.ts:3:36 - error TS2307: Cannot find module '@chakra-ui/toast/src' or its corresponding type declarations.

3 import { ToastProviderProps } from "@chakra-ui/toast/src";
                                     ~~~~~~~~~~~~~~~~~~~~~~

node_modules/@chakra-ui/react/dist/declarations/src/chakra-provider.d.ts:14:39 - error TS2307: Cannot find module '@chakra-ui/theme/src/components' or its corresponding type declarations.

14             components: typeof import("@chakra-ui/theme/src/components");
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@chakra-ui/tabs/dist/declarations/src/use-tabs.d.ts:8:25 - error TS2307: Cannot find module '@chakra-ui/descendant/src/use-descendant' or its corresponding type declarations.

8     descendants: import("@chakra-ui/descendant/src/use-descendant").UseDescendantsReturn;
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is likely due to not exposing `src` anymore in the resulting packages but still including the type declarations source.

**Comment by oncet** [comment]
I'm experiencing the same errors as well when trying to build the project.

**Comment by TylerAPfledderer** [comment]
Hey @Averethel! What happens if you add `"skipLibCheck": true` to your tsconfig `compilerOptions`?

**Comment by jakeboone02** [comment]
@TylerAPfledderer I was experiencing the same thing (see the packages/chakra and packages/demo folders [here](https://github.com/react-querybuilder/react-querybuilder/tree/react-18)) and `"skipLibCheck": true` in tsconfig.json...I don't want to say "solved" the problem, but... _avoided_ the problem, I guess? Still should be fixed, but seems to be ok for now in my case.

**Comment by Averethel** [comment]
@TylerAPfledderer `"skipLibCheck": true` is a workaround that works for the time being. It would be great if we can fix this since we're relying on a few internal libraries and, in the long run, it's not a great one for our use-case.

I'd be happy to prepare a fix if I can have a bit of direction.

**Comment by paulopontovaz** [comment]
I've run into this issue as well but only after I updated my React version to 18. Thought I'd mention it.

**Comment by Nivsha08** [comment]
Run into this issue too, after upgrading to React 18 (and Webpack 5). In my case `craco build` failed over not recognizing `.module.scss` files, but locally all's good. Thought it might be related to some `sass-loader` configuration but no luck.
