### ISSUE TITLE
Chakra UI CLI  v1.2.0 Generate theme typings problem with variants

### ISSUE THREAD

**Issue by violabg** [chakra-ui/chakra-ui#3308]
I'm trying to generate typings with the latest version of chakra 1.3 and Chakra UI CLI  v1.2.0.
but I'm getting an error 

`error TS2322: Type '{ baseStyle: { fontFamily: string; fontSize: string; fontWeight: number; textTransform: string; }; sizes: { sm: { fontSize: string; }; md: { fontSize: string; }; lg: { fontSize: string; }; }; variants: { outline: (props: any) => { ...; }; ... 5 more ...; linkSecondary: (props: any) => { ...; }; }; defaultProps: { .....' is not assignable to type 'DeepThemeExtension<Partial<{ baseStyle: { lineHeight: string; borderRadius: string; fontWeight: string; _focus: { boxShadow: string; }; _disabled: { opacity: number; cursor: string; boxShadow: string; }; _hover: { _disabled: { ...; }; }; }; variants: { ...; }; sizes: { ...; }; defaultProps: { ...; }; }>, ComponentSt...'.`

## 💥 Steps to reproduce

```js
export const Button = {
  variants: {
    outline: (props: any) => {
      const { colorScheme: c } = props;
      return {
        borderColor: `${c}.500`,
        color: `${c}.500`,
        _hover: {
          bg: `${c}.500`,
          borderColor: `${c}.500`,
          color: "white"
        }
      };
    },
  }
};
```

chakra-cli tokens src/theme/index.ts

## 🧐 Expected behavior

if you do this

```js
export const Button = {
  variants: {
    outline: {
        borderColor: `red.500`,
        color: `red.500`,
        _hover: {
          bg: `red.500`,
          borderColor: `red.500`,
          color: "white"
        }
     }
  }
};
```

works.
it also works in chakra 1.2 with Chakra UI CLI  v1.1.0

**Comment by luigiminardim** [comment]
I know this has been closed for some time, but recently I'm trying to just copy and paste the components theme definitions from the  [Chakra-UI source](https://github.com/chakra-ui/chakra-ui/tree/main/packages/theme/src/foundations) and this error persists. I'm using Chakra UI CLI  v1.3.0.

**Comment by with-heart** [comment]
@luigiminardim If you could provide a reproduction of what you're trying to do, that would help quite a bit!

**Comment by luigiminardim** [comment]
> I know this has been closed for some time, but recently I'm trying to just copy and paste the components theme definitions from the [Chakra-UI source](https://github.com/chakra-ui/chakra-ui/tree/main/packages/theme/src/foundations) and this error persists. I'm using Chakra UI CLI v1.3.0.

# Steps to reproduce: 
1. Create a Nextjs project;
    ```sh
    yarn create next-app chakra-ui-bug-demo && cd chakra-ui-bug-demo
    ```
2. Set Nextjs to use TypeScript;
    ```sh
    touch tsconfig.json && yarn add --dev typescript @types/react && yarn dev
    ```
3. Install chakra-u/cli and add two the two new scripts in `package.json`
    ```sh
    yarn add --dev @chakra-ui/cli
    ```
    ```json
    // package.json
    
    "scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start",
        "gen:theme-typings": "chakra-cli tokens ./theme",
        "postinstall": "npm run gen:theme-typings"
    }
    ```
4. Add the following files:
    ```ts
    // theme/index.ts  
    
    import { extendTheme } from "@chakra-ui/react";
    import Button from "./button"

    export const theme = extendTheme({
     components: {
        Button
      }
    })
    ```
    ```ts
    // theme/button.ts
    // copy contents from this URL: 
    // https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/button.ts
    ```
5. Generate the typings:
    ```sh
    yarn install
    ```
    
## Result
![Screenshot from 2021-04-05 20-03-33](https://user-images.githubusercontent.com/37146539/113637203-6ddedb00-964a-11eb-93f8-48b04e408a83.png)

Type '{ baseStyle: { lineHeight: string; borderRadius: string; fontWeight: string; _focus: { boxShadow: string; }; _disabled: { opacity: number; cursor: string; boxShadow: string; }; _hover: { _disabled: { bg: string; }; }; }; variants: { ...; }; sizes: { ...; }; defaultProps: { ...; }; }' is not assignable to type 'DeepThemeExtension<Partial<{ baseStyle: { lineHeight: string; borderRadius: string; fontWeight: string; _focus: { boxShadow: string; }; _disabled: { opacity: number; cursor: string; boxShadow: string; }; _hover: { _disabled: { ...; }; }; }; variants: { ...; }; sizes: { ...; }; defaultProps: { ...; }; }>, ComponentSt...'.
  The types of 'variants.ghost' are incompatible between these types.
    Type '(props: Dict) => { color: any; _hover: { bg: any; }; _active: { bg: any; }; bg?: undefined; } | { color: any; bg: string; _hover: { bg: any; }; _active: { bg: any; }; }' is not assignable to type 'DeepThemeExtension<Partial<{ color: any; _hover: { bg: any; }; _active: { bg: any; }; bg?: undefined; } | { color: any; bg: string; _hover: { bg: any; }; _active: { bg: any; }; }>, CSSWithMultiValues | ThemeComponentFunction<...> | SystemStyleObjectRecord | ThemeComponentFunction<...>>'.
      Value of type '(props: Dict) => { color: any; _hover: { bg: any; }; _active: { bg: any; }; bg?: undefined; } | { color: any; bg: string; _hover: { bg: any; }; _active: { bg: any; }; }' has no properties in common with type 'DeepThemeExtension<Partial<{ color: any; bg: string; _hover: { bg: any; }; _active: { bg: any; }; }>, CSSWithMultiValues | ThemeComponentFunction<CSSObject, ChakraTheme> | SystemStyleObjectRecord | ThemeComponentFunction<...>>'. Did you mean to call it?ts(2322)
index.d.ts(294, 9): The expected type comes from property 'Button' which is declared here on type 'ThemeComponents & DeepThemeExtension<Partial<{ Accordion: { parts: string[]; baseStyle: { container: { borderTopWidth: string; borderColor: string; _last: { borderBottomWidth: string; }; }; button: { ...; }; panel: { ...; }; icon: { ...; }; }; }; ... 38 more ...; FormError: { ...; }; }>, ThemeComponents>'
