### ISSUE TITLE
[TypeScript] Portal component no longer has containerRef defined

### ISSUE THREAD

**Issue by narkeeso** [chakra-ui/chakra-ui#3284]
# 🐛 Bug report

```
Type '{ children: Element; containerRef: RefObject<HTMLElement | null>; }' is not assignable to type 'IntrinsicAttributes & PortalProps'.
  Property 'containerRef' does not exist on type 'IntrinsicAttributes & PortalProps'.  TS2322
```

This code was working fine in 1.0 so there must have been a recent change to Portal typings.

## 💥 Steps to reproduce

Use a `Portal` component and its attribute `containerRef`

## 💻 Link to reproduction

 https://codesandbox.io/s/chakra-portal-containerref-typescript-issue-uine5?file=/src/App.tsx

## 🧐 Expected behavior

Expect for type check to pass.

**Comment by narkeeso** [comment]
Actually, looks like it's an issue on our end. Ignore
