### ISSUE TITLE
{ motion } is not a function in Framer Motion 6.2.8

### ISSUE THREAD

**Issue by alexastef** [chakra-ui/chakra-ui#5735]
### Description

When I run my app after updating Chakra-ui to 1.8 and Framer to 6.2.8, I receive a TypeError: Object(...) is not a function, referring to { motion } from framer

### Link to Reproduction

https://github.com/chakra-ui/chakra-ui#codesandbox-templates

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.8.6

### Browser

Google Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I've also tried installing Framer back down to version 3.3 and the issue still persists

var Section = motion(chakra.section);

**Comment by omar-bear** [comment]
i dont understand the fix i have the same error and i need to stay on `1.8.8` version 

i upgraded from `1.0.1` to `1.8.8`

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/80390318/216571909-60cf588b-635e-4fab-8be0-2246bdd7e43b.png">
