### ISSUE TITLE
has no exported member 'ChakraStyleProps'. when upgrading from 1.0.4 > 1.3.2

### ISSUE THREAD

**Issue by hutber** [chakra-ui/chakra-ui#3358]
I have just upgraded my package and TS is generating the following error:

```
Module '"../../../node_modules/@chakra-ui/react/dist/types"' has no exported member 'ChakraStyleProps'.

2 import { ChakraStyleProps, HStack, useBreakpointValue } from "@chakra-ui/react"
```

#### Full Error

```
components/pages/blog/Category.tsx:2:10 - error TS2305: Module '"../../../node_modules/@chakra-ui/react/dist/types"' has no exported member 'ChakraStyleProps'.

2 import { ChakraStyleProps, HStack, useBreakpointValue } from "@chakra-ui/react"
           ~~~~~~~~~~~~~~~~

theme/index.ts:26:34 - error TS2345: Argument of type '{ fonts: { demi: string; book: string; light: string; freight: string; }; fontWeights: { light: number; normal: number; medium: number; boldish: number; bold: number; }; fontSizes: { 13: string; 8: string; 5: string; ... 5 more ...; "-2": string; }; ... 6 more ...; components: { ...; }; }' is not assignable to parameter of type 'ThemeOverride'.
  Type '{ fonts: { demi: string; book: string; light: string; freight: string; }; fontWeights: { light: number; normal: number; medium: number; boldish: number; bold: number; }; fontSizes: { 13: string; 8: string; 5: string; ... 5 more ...; "-2": string; }; ... 6 more ...; components: { ...; }; }' is not assignable to type 'DeepThemeExtension<{ components: { Accordion: { parts: string[]; baseStyle: { container: { borderTopWidth: string; borderColor: string; _last: { borderBottomWidth: string; }; }; button: { fontSize: string; _focus: { boxShadow: string; }; _hover: { ...; }; _disabled: { ...; }; px: number; py: number; }; panel: { ...;...'.
    The types of 'breakpoints.toString' are incompatible between these types.
      Type '(() => string) & (() => string)' is not assignable to type 'string'.

26 export const theme = extendTheme(appTheme)
                                    ~~~~~~~~


Found 2 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky > pre-commit hook failed (add --no-verify to bypass)

```

#### Theme File

```
import { extendTheme } from "@chakra-ui/react"

import * as themeConfig from "./themeConfig"

import { components } from "./components"
import { colors } from "./colors"
import { breakpoints } from "./breakpoints"
import { fontVariants } from "./fontVariants"

const styles = {
  global: {
    ...fontVariants,
    body: {
      ...fontVariants,
    },
  },
}

const appTheme = {
  styles,
  breakpoints,
  colors,
  components,
  ...themeConfig,
}
export const theme = extendTheme(appTheme)
```

**Comment by hutber** [comment]
I believe it could be something to do with the breakpoints:

#### breakpoints.ts

```
// Following the Material UI breakpoints https://material-ui.com/customization/breakpoints/
import { createBreakpoints } from "@chakra-ui/theme-tools"

export const breakpointValues = {
  sm: "34.99rem",
  md: "47.99rem",
  lg: "63.99rem",
  xl: "119.99rem",
}
export const breakpoints = createBreakpoints(breakpointValues)

export const hookBreakpoints = {
  mobile: `(max-width: ${breakpoints.sm})`,
  mobileMin: `(min-width: ${breakpoints.sm})`,
  mobileMax: `(max-width: ${breakpoints.md})`,
  tablet: `(min-width: ${breakpoints.md}) and (max-width: ${breakpoints.lg})`,
  tabletMax: `(max-width: ${breakpoints.lg})`,
  desktop: `(min-width: ${breakpoints.lg}) and (max-width: ${breakpoints.xl})`,
  desktopMax: `(max-width: ${breakpoints.xl})`,
  extraLarge: `(min-width: ${breakpoints.xl})`,
}
```

**Comment by TimKolberger** [comment]
Could you please create a reproduction for that?
This codesandbox uses `createBreakpoints` without errors: https://codesandbox.io/s/chakra-ui-custom-breakpoints-jx5dg?file=/src/App.tsx

**Comment by hutber** [comment]
Thanks Tim, I spent a fair bit of time trying to reproduce this... I'm having a hard time, so if I haven't nailed it on Monday I'll close this issue, thanks!

**Comment by TimKolberger** [comment]
@hutber maybe this comment will help you: https://github.com/chakra-ui/chakra-ui/issues/3372#issuecomment-778795289

**Comment by hutber** [comment]
It seems I have 51 TS errors I need to fix before I can confirm if this helps :) But it certainly looks promising...

**Comment by hutber** [comment]
So it seems that the export has changed from:
`ChakraStyleProps`
to
`StyleProps`
However I do still have the inital error seen in #3372 too

**Comment by segunadebayo** [comment]
Yes, please replace the import to `StyleProps`.
