### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by jitenderchand1** [chakra-ui/chakra-ui#3812]
After upgrading to `@chakra-ui/react": "^1.5.1`, I am getting the following error.  is it an issue with the version or do I need to update any other packages?

It was working fine with `@chakra-ui/react": "^1.1.5`

<img width="1072" alt="Screen Shot 2021-04-14 at 1 23 40 PM" src="https://user-images.githubusercontent.com/19687185/114674535-f5041100-9d24-11eb-946c-2cc8f5325a40.png">

I am also getting typescript errors after updating the package. But for now I have put `any` and it working thought is it not good approach to fix it.

```
const radii: ObjectOrArray<CSS.BorderRadiusProperty<string>> = {
  // chakra values
  none: '0',
  sm: '0.125rem',
  md: '0.25rem',
  lg: '0.5rem',
  xl: '0.75rem',
  '2xl': '1rem',
  '3xl': '1.25rem',
  full: '9999px'
};
```

I have put `any` in place of `ObjectOrArray<CSS.BorderRadiusProperty<string>>` to fix it

<img width="996" alt="Screen Shot 2021-04-13 at 8 01 18 PM" src="https://user-images.githubusercontent.com/19687185/114675019-6d6ad200-9d25-11eb-8f3f-d27af5c7acf7.png">

**Comment by segunadebayo** [comment]
Hi @jitenderchand1,

Kindly upgrade to the latest version of `framer-motion`. Regarding the TypeScript error, please `ThemeOverrides["radii"]` instead. If the error persists, please provide a reproduction in CodeSandbox.

**Comment by jitenderchand1** [comment]
After upgrading framer-motion to `^4.1.3`. I am getting the following error. We are using `styled-system` in the project with chakra UI. 

"styled-system": "^5.1.5",
"@chakra-ui/react": "^1.5.0",
"@emotion/react": "^11.1.5",
"@emotion/styled": "^11.3.0",
"@styled-system/css": "^5.1.5",
"@styled-system/theme-get": "^5.1.2",


<img width="1096" alt="Screen Shot 2021-04-15 at 9 36 27 AM" src="https://user-images.githubusercontent.com/19687185/114812801-62b84780-9dce-11eb-8d62-500998698c5c.png">

**Comment by damingerdai** [comment]
i also met this issue with `@chakra-ui/react: 1.6.2"

**Comment by with-heart** [comment]
If one of you can provide a CodeSandbox reproduction of the problem, I'll gladly reopen.

**Comment by jitenderchand1** [comment]
https://github.com/chakra-ui/chakra-ui/issues/3845
