### ISSUE TITLE
Typescript error when passing ref to the `CheckboxGroup` component

### ISSUE THREAD

**Issue by tom2drum** [chakra-ui/chakra-ui#10663]
### Description

I am trying to update to `v3.33.0`, but I am encountering a TypeScript error stating that `CheckboxGroup` doesn't have the `ref` property. The same code works in version `v3.15.0`.

<img width="1418" height="508" alt="Image" src="https://github.com/user-attachments/assets/9e6e5261-8f87-4df0-932e-be98406729ad" />

[Link to the code](https://github.com/blockscout/frontend/blob/fa7d3d12f9183f3f0959b3fecfe63a726b998a07/toolkit/chakra/checkbox.tsx#L38)

```cli
toolkit/chakra/checkbox.tsx:38:9 - error TS2322: Type '{ children: ReactNode; htmlSize?: number | undefined; htmlWidth?: string | number | undefined; htmlHeight?: string | number | undefined; htmlTranslate?: "yes" | "no" | undefined; ... 1131 more ...; orientation: "horizontal" | "vertical"; }' is not assignable to type 'IntrinsicAttributes & CheckboxGroupProps'.
  Property 'ref' does not exist on type 'IntrinsicAttributes & CheckboxGroupProps'.
```

### Link to Reproduction

https://github.com/blockscout/frontend/actions/runs/22346699873/job/64663037985

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

3.33.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
That's a good catch. Thanks for bringing it up.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
