### ISSUE TITLE
TypeError: (0 , _utils.compose) is not a function

### ISSUE THREAD

**Issue by lednhatkhanh** [chakra-ui/chakra-ui#3009]
Package version:

```
"@chakra-ui/icons": "1.0.2",
"@chakra-ui/react": "1.1.0",
```

It's happening with a Next.js project when running `next dev`

**Comment by lednhatkhanh** [comment]
I checked again and this only happens when using `react@16` in a next.js project

**Comment by anubra266** [comment]
Nah, I use react 17, in a Create react app, same issue

**Comment by poizoncc** [comment]
Same
```
[!] Error: 'compose' is not exported by ../../node_modules/@chakra-ui/utils/dist/esm/index.js, imported by ../../node_modules/@chakra-ui/styled-system/dist/esm/utils/logical-prop.js
```

**Comment by objmj-itminds** [comment]
Updated from @chakra-ui/react 1.1.2 to 1.1.3 as the only dependency update also brings forth this error

I have a pipeline [here](https://github.com/IT-Minds/client_comby_oilcontrols/pull/12/checks?check_run_id=1680641017) should it help. The main takeaway is this stack trace.

```
 TypeError: (0 , _utils.compose) is not a function

    > 1 | import {
        | ^
      2 |   Button,
      3 |   Container,
      4 |   Heading,

      at logicalTransform (node_modules/@chakra-ui/styled-system/src/utils/logical-prop.ts:27:22)
      at Object.logical (node_modules/@chakra-ui/styled-system/src/utils/logical-prop.ts:43:16)
      at Object.<anonymous> (node_modules/@chakra-ui/styled-system/src/config/position.ts:19:23)
      at Object.<anonymous> (node_modules/@chakra-ui/styled-system/src/config/index.ts:8:1)
      at Object.<anonymous> (node_modules/@chakra-ui/styled-system/src/index.ts:1:1)
      at Object.<anonymous> (node_modules/@chakra-ui/system/src/index.ts:2:1)
      at Object.<anonymous> (node_modules/@chakra-ui/react/src/chakra-provider.tsx:3:1)
      at Object.<anonymous> (node_modules/@chakra-ui/react/src/index.tsx:1:1)
      at Object.<anonymous> (src/components/Demo/Demo.tsx:1:1)
      at Object.<anonymous> (src/components/Demo/Demo.test.tsx:8:1)
  ```

**Comment by MichaelGrigoryan25** [comment]
Having the same issue after upgrading to 1.1.3

**Comment by with-heart** [comment]
The cause for this issue is similar to the cause of #3006. The `compose` function was added but a changeset file was not, meaning our automated release process had no way to detect that it needed to publish a new version of `@chakra-ui/utils`. Will open a PR shortly to fix this.

**Comment by segunadebayo** [comment]
Thanks for catching this @with-heart. This was my bad.

**Comment by segunadebayo** [comment]
Releasing a new version shortly

**Comment by MichaelGrigoryan25** [comment]
Thanks for the fix!

**Comment by ugcgt** [comment]
في اثنين، ١١ يناير، ٢٠٢١ في ٧:٤١ م، كتب Michael Grigoryan <
notifications@github.com>:

**Comment by objmj-itminds** [comment]
Can confirm the fix worked.
