### ISSUE TITLE
[Select] Property 'variant' does not exist on type

### ISSUE THREAD

**Issue by scon-io** [chakra-ui/chakra-ui#1245]
**Describe the bug**

In 1.0.0-next.5 and 1.0.0-next.6, `variant` prop of `Select` component throws type error in typescript. It worked in 1.0.0-next.4

```
<Select variant="filled" />
```

Type `'{ children: any; variant: string; }'` is not assignable to type `'IntrinsicAttributes & Pick<SelectProps, "title" | "form" | "p" | "slot" | "style" | "children" | "size" | "className" | "color" | "height" | ... 496 more ... | "iconColor"> & RefAttributes<...>'`. Property `'variant'` does not exist on type `'IntrinsicAttributes & Pick<SelectProps, "title" | "form" | "p" | "slot" | "style" | "children" | "size" | "className" | "color" | "height" | ... 496 more ... | "iconColor"> & RefAttributes<...>'`.

**Comment by segunadebayo** [comment]
Good catch @scon-io.

I've just fixed this. We'll publish an update shortly.
