### ISSUE TITLE
__framermotion.motion.custom is not a function error when wrapping next js _app inside ChakraProvider component

### ISSUE THREAD

**Issue by Nouhack** [chakra-ui/chakra-ui#3624]
# 🐛 Bug report

After installing chakra ui from the officiel doc and wrap _app component inside ChakraProvider ,  when i start dev server i got this error : 

=======================
 TypeError: _framerMotion.motion.custom is not a function
    at Object.<anonymous> (/home/nouhack/Desktop/projects/app1/node_modules/@chakra-ui/checkbox/dist/cjs/checkbox-icon.js:20:38)

======================
and i noticed that the error comes when i import ChakraProvider from @chakra-ui/react

## 💥 Steps to reproduce

STEPS :
1. create next js app with   ==>  create-next-app
2. install chakra ui with      ==> npm i @chakra-ui/react @emotion/react @emotion/styled framer-motion
3.start dev server with       ==> npm run dev
4. browser Error message  : Internal Server Error  &&console error message :   TypeError: _framerMotion.motion.custom is not a function
    at Object.<anonymous> (/home/nouhack/Desktop/projects/app1/node_modules/@chakra-ui/checkbox/dist/cjs/checkbox-icon.js:20:38)

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/busy-dream-dtvvi

## 🧭 Possible Solution
start the dev server normally

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |     1.3.4       |
| Browser          |     mozilla       |
| Operating System |      manjaro      |

## 🌍dependecies

| Software         | Version(s) |
| ---------------- | ---------- |
| @chakra-ui/react        |     ^1.3.4     |
| @emotion/react          |     ^11.1.5       |
| @emotion/styled       |      ^11.1.5   |
| framer-motion       |     ^4.0.0     |
| next       |     10.0.9     |
| react       |     17.0.1     |
| react-dom       |     17.0.1    |

**Comment by ubenzer** [comment]
Hi @Nouhack 👋 ,
I am getting the same error in one of my pet projects. Did you manage to solve this?

**Comment by w1r3d7** [comment]
Same error 😒

**Comment by joshuaalpuerto** [comment]
@ubenzer I thinks this issue is related to [this](https://github.com/chakra-ui/chakra-ui/issues/3618). For now you can downgrade `framer-motion` to `v3.10.6`.

**Comment by edshav** [comment]
I am getting the same error :-(

**Comment by Nouhack** [comment]
as @joshuaalpuerto  said the problem was with framer motion 4 , currently it doesn't work with chakra-ui 1.3.4 , solution is to install `"framer-motion": "^3.10.6"` ==> `yarn add framer-motion@3.10.6` , same probleme was solved [here](https://github.com/chakra-ui/chakra-ui/issues/3618)
