### ISSUE TITLE
[Accordion] AccordionItem - defaultIsOpen does not exist

### ISSUE THREAD

**Issue by ganeshkrishnasharma** [chakra-ui/chakra-ui#1426]
`Property 'defaultIsOpen' does not exist on type 'IntrinsicAttributes & Pick<AccordionItemProps` - the defaultIsOpen property seems to be missing in version `1.0.0-rc.0` - Please check this issue :)

**Comment by with-heart** [comment]
I'm not sure when this prop disappeared. Do you have a version that it last worked for you?

**Comment by ganeshkrishnasharma** [comment]
@with-heart , it was working in v 0.8.0 , Recently after upgrade to v 1 , its disappeared.

**Comment by dodas** [comment]
Is this property needed? We have `index` and `defaultIndex` on `<Accordion>`, so I think this property is not really needed and docs can just be updated to remove it.

**Comment by ganeshkrishnasharma** [comment]
@dodas , defaultIndex may not be able to replace defaultIsOpen in all the cases i.e u have an iteration over `AccordionItem` and want certain(more than one) items to be open based a condition - in such cases defaultIsOpen is needed. And its a property of `AccordionItem`

**Comment by with-heart** [comment]
You could imitate that functionality without needing a prop on `AccordionItem`: https://codesandbox.io/s/angry-aryabhata-nvi40?file=/src/App.tsx

**Comment by dodas** [comment]
Or, without reduce:
```ts
const items = [
  { button: "Section 1", panel: "Panel 1", defaultIsOpen: true },
  { button: "Section 2", panel: "Panel 2" },
  { button: "Section 3", panel: "Panel 3" },
  { button: "Section 4", panel: "Panel 4", defaultIsOpen: true }
];

const indexes = items
  .map((item, itemIndex) => [item.defaultIsOpen, itemIndex] as const)
  .filter(([isOpen]) => isOpen)
  .map(([_, itemIndex]) => itemIndex);
```

**Comment by segunadebayo** [comment]
Hi @ganeshkrishnasharma,

The AccordionItem can no longer be used in isolation. You might need to still wrap it within `Accordion` and add the `defaultIndex` to that instead.

```jsx
<Accordion defaultIndex={0}>
  <AccordionItem />
</Accordion>
```

Feel free to also consider the other alternatives suggested by @dodas and @with-heart.

Cheers

**Comment by ganeshkrishnasharma** [comment]
Thanks much, will check on these suggestions :) @segunadebayo @with-heart @dodas

**Comment by dodas** [comment]
@segunadebayo So should we remove `isOpen` property from `<AccordionItem>` to keep it consistent?
Then, we can remove both `isOpen` and `defaultIsOpen` from AccordionItem's docs.

**Comment by with-heart** [comment]
@dodas I was going to say that it still needs those props because `Accordion` clones its children (which should all be `AccordionItem`) and injects it:

https://github.com/chakra-ui/chakra-ui/blob/7c66620bf4e01ad5ef5c8589c5712c805a220a70/packages/accordion/src/use-accordion.ts#L120-L126

but on second though, I don't think `AccordionItem` to have those props in order for cloning to still work. I'll look into it.

**Comment by with-heart** [comment]
Actually duh, it does still need it because `AccordionItem` accesses them internally.

**Comment by dodas** [comment]
Couldn't `AccordionItem` access it though context?

**Comment by ahmedshantodev** [comment]
@ganeshkrishnasharma  thanks 🖤
