### ISSUE TITLE
disabled attribute doesn't work on <Button>

### ISSUE THREAD

**Issue by BANOnotIT** [chakra-ui/chakra-ui#7905]
### Description

When I update `@chakra-ui/button` from 2.0.13 to 2.1.0 disable attribute doesn't work because of https://github.com/chakra-ui/chakra-ui/commit/0f376650efce9eb2d2cba3484ffe4e3a73364504. That's violation of SemVer because:
> MINOR version when you add functionality in a backward compatible manner

### Link to Reproduction

https://example.com

### Chakra UI Version

2.8.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by ShawnFumo** [comment]
Wanted to add that this ended up being a big issue for our company. We upgraded Chakra a few weeks ago, not realizing that this update broke most of our form buttons from disabling during dialog submissions. So we've had all kinds of data issues in production from people double-clicking the submit button, requiring time from people in the ops department, coordinating with multiple clients, etc.

Not only is it a semver issue, but it doesn't look like the change even got into the changelog? I searched through each version on https://chakra-ui.com/changelog/ and don't see the note from `.changeset/empty-ravens-rescue.md` in there anywhere. And if doing such a fundamental change, why not use Omit to remove the `disabled` property from those allowed on Button? That would have at least caused a compilation error after the update. Or even a warning in the console to say it is being ignored like what React does for missing keys on collections and such.

Yes, the docs don't seem to mention `disabled` at all, and yes we could have had more extensive Cypress tests to test for double-clicks, but if `disabled` and `isDisabled` are both listed as options in TypeScript and one has been working for at least a year, you don't expect that a simple library upgrade will cause your buttons to stop disabling with no warning.

**Comment by Philzen** [comment]
@BANOnotIT  #8462 has been merged, `disabled` prop on button works again, you can test that out in the LiveCoding-view here:  https://chakra-ui-website-ptekgabqh-chakra-ui.vercel.app/docs/components/button

If satisfied, you may close this issue, the fix should be shipping with Chakra 2.8.3.

**Comment by BANOnotIT** [comment]
It's great! But since this thing took so long to revert we just migrated to isDisabled so I don't have code to check whether it is fully compatible.

I suppose the issue can be closed

**Comment by coxato** [comment]
`isDisabled` insted of `disabled` worked for me

**Comment by Philzen** [comment]
> `isDisabled` insted of `disabled` worked for me

@coxato Worked to do what exactly? If you refer to just disabling the button, surely `isDisabled` works. That is not the scope of this issue though – it is around SemVer violations, [typescript mismatches](https://github.com/chakra-ui/chakra-ui/issues/7269) and [accessibility](https://github.com/chakra-ui/chakra-ui/issues/7965).

**Comment by coxato** [comment]
@Philzen hi, yes it was just to disable a button, inside a basic component, not inside a form.
