### ISSUE TITLE
TypeScript: Expression produces a union type that is too complex to represent. ts(2590)

### ISSUE THREAD

**Issue by vincentbriglia** [chakra-ui/chakra-ui#3714]
# 🐛 Bug report

in some cases, instead of updating the theme, we want to change some defaults in components directly, to fit a more opinionated approach, and proxy ChakraUI components ... f.ex:

```
import { ModalBody as ModalBodyComponent, ModalBodyProps } from '@chakra-ui/modal';
import { forwardRef } from '@chakra-ui/system';
import * as React from 'react';

export const ModalBody = forwardRef<ModalBodyProps, 'div'>((props, ref) => {
  return <ModalBodyComponent pb={6} {...props} ref={ref} />;
});
```
## 💥 Steps to reproduce

components with a lot of props (number unknown) seem to be the culprit

## 💻 Link to reproduction
Note, I cannot seem to reproduce this on Codesandbox, but I can reproduce this locally in a clean project, So i suggest cloing the codesandbox locally.
CodeSandbox reproduction: https://codesandbox.io/s/summer-night-bmzsl?file=/src/ModalBody.tsx

## 🧐 Expected behavior

union types should not be extra complex using this method

## 🧭 Possible Solution

n/a

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI        |      "@chakra-ui/modal": "1.7.0", "@chakra-ui/system": "1.4.0",    "@chakra-ui/utils": "1.4.0",  |
| Browser          |   n/a    |
| Operating System |  MacOS   |

## 📝 Additional information

could be related to #3706

**Comment by with-heart** [comment]
You likely can't reproduce it in CSB because it's using a different version of TypeScript. It seems that somewhere around TypeScript v4.2.x, something changed that is occasionally throwing this error. It's been reported on Discord as well, but unsure of root cause yet.

**Comment by vincentbriglia** [comment]
TypeScript version 4.2.3, using the TypeScript version installed by my local package.json instead of VSCode's internal TypeScript version.

**Comment by vincentbriglia** [comment]
https://github.com/microsoft/TypeScript/issues/42790

**Comment by with-heart** [comment]
@vincentbriglia Good find! Thank you!

**Comment by Daggy1234** [comment]
Hey so I'm habing the same problem with this Jsx snippet.

```jsx
<MenuButton
                                        size="lg"
                                        borderColor="transparent"
                                        variant="outline"
                                        _hover={{}}
                                        as={Button}
                                        rightIcon={<FaChevronDown />}>
                                        <Avatar size="md" src={user.photoURL} alt={user.name} />
                                    </MenuButton>
```

`Expression produces a union type that is too complex to represent.ts(2590)`

I'm on:
"@chakra-ui/react": "^1.1.0",
"next": "10.0.4",
"typescript": "^4.1.2"

**Comment by joel1st** [comment]
I can confirm that this error is still occuring in our project. This error only appears to surface on typescript `4.2.x` and higher. (`4.1.6` runs fine in our project). We are using `"@chakra-ui/react": "^1.6.5"`

A simple case:
```
import { Spinner, SpinnerProps } from '@chakra-ui/react';
import React from 'react';

export function Loading(props: SpinnerProps) {
  return (
    <Spinner
      thickness="4px"
      speed="0.65s"
      emptyColor="gray.200"
      color="brand.blue"
      size="xl"
      {...props}
    />
  );
}
```

**Comment by milancr** [comment]
has anyone solved this?

**Comment by FreePhoenix888** [comment]
1. Open a JavaScript or TypeScript file in VS Code.
2. In the VS Code command palette, run the TypeScript: Select TypeScript version command.
3. Make sure you have `Use workspace version` selected

**Comment by FreePhoenix888** [comment]
@aytek, @timreach, @brunolucena, @homfarnam, @valekuro, ralph-@interworldhighway, @regisfoucault, @kubido, @PaulineMyTutor, I see your reactions on my answer and I would be glad to see the same reaction on my question+answer about this topic stackoverflow. I hope it will help other people to come to that solution without looking for it too long :)

**Comment by ashutosh887** [comment]
@vincentbriglia @with-heart @joel1st @Daggy1234 @milancr Any solution to this if worked out for you?
It's appearing in mine too...

**Comment by FreePhoenix888** [comment]
> 

https://github.com/chakra-ui/chakra-ui/issues/3714#issuecomment-1357167913

**Comment by victorvianaom** [comment]
> # Solution
> 1. Open a JavaScript or TypeScript file in VS Code.
> 2. In the VS Code command palette, run the TypeScript: Select TypeScript version command.
> 3. Make sure you have `Use workspace version` selected
> 
> UPD: I have created a [question+answer](https://stackoverflow.com/questions/74847053/how-to-fix-expression-produces-a-union-type-that-is-too-complex-to-represent-t) on stackoverflow. I hope it helps someone :)

It works, thanks!

**Comment by indian-boy** [comment]
> # Solution
> 1. Open a JavaScript or TypeScript file in VS Code.
> 2. In the VS Code command palette, run the TypeScript: Select TypeScript version command.
> 3. Make sure you have `Use workspace version` selected
> 
> UPD: I have created a [question+answer](https://stackoverflow.com/questions/74847053/how-to-fix-expression-produces-a-union-type-that-is-too-complex-to-represent-t) on stackoverflow. I hope it helps someone :)

You are my hero. Thanks!

**Comment by nhutruong-beycons** [comment]
> # Solution
> 1. Open a JavaScript or TypeScript file in VS Code.
> 2. In the VS Code command palette, run the TypeScript: Select TypeScript version command.
> 3. Make sure you have `Use workspace version` selected
> 
> UPD: I have created a [question+answer](https://stackoverflow.com/questions/74847053/how-to-fix-expression-produces-a-union-type-that-is-too-complex-to-represent-t) on stackoverflow. I hope it helps someone :)

Thank you for your solution, but still an error for me.
![image](https://user-images.githubusercontent.com/101889353/212538472-8297c0f5-3252-40cc-a0b7-cf51c1556e1a.png)

![image](https://user-images.githubusercontent.com/101889353/212538549-c779d387-24d1-44b4-89a7-232565b1a0a0.png)

**Comment by FreePhoenix888** [comment]
> > # Solution
> > 
> > 1. Open a JavaScript or TypeScript file in VS Code.
> > 2. In the VS Code command palette, run the TypeScript: Select TypeScript version command.
> > 3. Make sure you have `Use workspace version` selected
> > 
> > UPD: I have created a [question+answer](https://stackoverflow.com/questions/74847053/how-to-fix-expression-produces-a-union-type-that-is-too-complex-to-represent-t) on stackoverflow. I hope it helps someone :)
> 
> Thank you for your solution, but still an error for me. ![image](https://user-images.githubusercontent.com/101889353/212538472-8297c0f5-3252-40cc-a0b7-cf51c1556e1a.png)
> 
> ![image](https://user-images.githubusercontent.com/101889353/212538549-c779d387-24d1-44b4-89a7-232565b1a0a0.png)

Please show your output of `npm list` command

**Comment by alexdanilowicz** [comment]
@FreePhoenix888  - I'm experiencing the same as @nhutruong-beycons. Both VS code ts version and workspace ts version on `4.9.4` and also using `@chakra-ui/react@2.4.5`, where spreading props seems to cause this issue.

output of npm list:
```
nextjs@0.1.0
├── @chakra-ui/react@2.4.5
├── @emotion/react@11.10.5
├── @emotion/styled@11.10.5
├── @mdx-js/loader@2.2.1
├── @mdx-js/react@2.2.1
├── @next/font@13.0.7
├── @next/mdx@13.1.1
├── @react-three/drei@9.48.1
├── @react-three/fiber@8.9.1
├── @supabase/auth-helpers-nextjs@0.5.2
├── @supabase/auth-helpers-react@0.3.1
├── @supabase/auth-ui-react@0.2.6
├── @supabase/supabase-js@2.2.2
├── @types/chrome@0.0.208
├── @types/node@18.11.17
├── @types/react-dom@18.0.9
├── @types/react@18.0.26
├── autoprefixer@10.4.13
├── axios@1.2.1
├── client-only@0.0.1
├── eslint-config-next@13.0.7
├── eslint@8.30.0
├── framer-motion@8.0.2
├── next@13.0.7
├── nextjs-google-analytics@2.2.2
├── postcss@8.4.20
├── react-dom@18.2.0
├── react-icons@4.7.1
├── react-multi-email@1.0.6
├── react@18.2.0
├── server-only@0.0.1
├── tailwindcss@3.2.4
├── three@0.147.0
└── typescript@4.9.4
```

**Comment by ashutosh887** [comment]
@FreePhoenix888 @nhutruong-beycons @indian-boy  

This **USE WORKSPACE VERSION** doesn't come in my VScode to select. 
Is there any way to enable it?

**Comment by alexdanilowicz** [comment]
@ashutosh887 , see the [stackoverflow](https://stackoverflow.com/questions/74847053/how-to-fix-expression-produces-a-union-type-that-is-too-complex-to-represent-t) linked above

> If there is no `Use workspace` version option, make sure you have typescript in your dependencies in package.json and you have installed your dependencies by running npm install or yarn. If you still do not have it - add `typescript.enablePromptUseWorkspaceTsdk: true` to .vscode/settings.json

**Comment by FreePhoenix888** [comment]
> @FreePhoenix888 - I'm experiencing the same as @nhutruong-beycons. Both VS code ts version and workspace ts version on `4.9.4` and also using `@chakra-ui/react@2.4.5`, where spreading props seems to cause this issue.
> 
> I can also confirm I have ` "typescript.enablePromptUseWorkspaceTsdk": true` in my tsconfig.json and I have restarted my vscode. I have selected use the workspace ts version in my vscode command prompt.
> 
> output of npm list:
> 
> ```
> nextjs@0.1.0
> ├── @chakra-ui/react@2.4.5
> ├── @emotion/react@11.10.5
> ├── @emotion/styled@11.10.5
> ├── @mdx-js/loader@2.2.1
> ├── @mdx-js/react@2.2.1
> ├── @next/font@13.0.7
> ├── @next/mdx@13.1.1
> ├── @react-three/drei@9.48.1
> ├── @react-three/fiber@8.9.1
> ├── @supabase/auth-helpers-nextjs@0.5.2
> ├── @supabase/auth-helpers-react@0.3.1
> ├── @supabase/auth-ui-react@0.2.6
> ├── @supabase/supabase-js@2.2.2
> ├── @types/chrome@0.0.208
> ├── @types/node@18.11.17
> ├── @types/react-dom@18.0.9
> ├── @types/react@18.0.26
> ├── autoprefixer@10.4.13
> ├── axios@1.2.1
> ├── client-only@0.0.1
> ├── eslint-config-next@13.0.7
> ├── eslint@8.30.0
> ├── framer-motion@8.0.2
> ├── next@13.0.7
> ├── nextjs-google-analytics@2.2.2
> ├── postcss@8.4.20
> ├── react-dom@18.2.0
> ├── react-icons@4.7.1
> ├── react-multi-email@1.0.6
> ├── react@18.2.0
> ├── server-only@0.0.1
> ├── tailwindcss@3.2.4
> ├── three@0.147.0
> └── typescript@4.9.4
> ```

I guess it is somehow related with the dependency hell. At first try `npm clean-install`. Does it help?

**Comment by RobinClowers** [comment]
I'm running into this issue with typescript 5.0.2. I'm not using VSCode, I see this when I run tsc:
```
$ yarn tsc
error TS2590: Expression produces a union type that is too complex to represent.

63   return <Heading fontSize="lg" fontWeight="600" p={CARD_PADDING} {...props} />;
```

My tsc version:
```
$ yarn tsc -v
yarn run v1.22.17
Version 5.0.2
```

**Comment by salemhilal** [comment]
Same here. It started happening when I upgraded to TSv5 and React v18 types (it worked fine with React 18 itself).

**Comment by salemhilal** [comment]
Ooooh I do think it's something about TypeScript v5 and Chakra. There's a minimum reproduceable case [here](https://www.typescriptlang.org/play?ts=5.1.0-dev.20230316#code/JYWwDg9gTgLgBAbzgYQgOxgQ2GgplOAXzgDMoIQ4ByAAQGMALTAaykwFoBXYAeil0x0YVANwAoMXXQBnePAC8cABQBKOPIB8cADyoM2PAR4aRQA) using the latest version of `@chakra-ui/react` and `@types/react`. It uses TS nightly since TypeScript 5 doesn't seem to be in the playground yet, but the effect is the same.

**Comment by ygorduraes** [comment]
Same here, after upgrading to v5.0.2 / ES2018.

What's interesting is that I'm getting this error only in my build on Digital Ocean, not locally:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/70910582/225838496-6030e83e-bb09-4529-ae3c-1c34d1f450e5.png">

<img width="414" alt="image" src="https://user-images.githubusercontent.com/70910582/225838749-6173b228-8647-43ac-8ece-da321cb992c2.png">

**Comment by faouziMohamed** [comment]
Going back to **typescript@4.9.5** till this this error getting solved.

**Comment by tonyc856** [comment]
I had the same issue today when I was trying to deploy my Nextjs project. 

`Type error: Expression produces a union type that is too complex to represent` on the Chakra UI components.

I was using `"@chakra-ui/react": "2.5.2"` and `"typescript": "5.0.2"`. Setting the 

Downgrading back to `@chakra-ui/react@2.5.1` and `typescript@4.9.5` did it for me and the error was gone during my deployment on Vercel.

**Comment by etarley** [comment]
Downgrading to @chakra-ui/react@2.5.1 and typescript@4.9.5 resolved the issue for me. I encountered the error in VSCode prior to deployment. @tonyc856, it's possible that the TypeScript version used by your editor is different from the one in your workspace, which might be causing the discrepancy.

**Comment by zgid123** [comment]
same issue, downgrade typescript to `4.9.5` to fix the error 😂

**Comment by parwiwisaw** [comment]
> 

Me too!

**Comment by OxBryte** [comment]
How did you get to downgrade it??

**Comment by Bismvrckz** [comment]
> How did you get to downgrade it??

you can change it in your package.json from "5.x.x" to "4.9.5", and just run "yarn install" or "npm i" again.

**Comment by tonyc856** [comment]
> How did you get to downgrade it??

@OxBryte you downgrade a package by running the command `npm upgrade <package_name>@<version>`

So if you want version 4.95 of Typecript, you can run `npm upgrade typescript@4.9.5`.

I know it says "upgrade" but it also handles downgrades as well.

**Comment by OxBryte** [comment]
Understood thanks ☺️

**Comment by isimmons** [comment]
First time using Chakra, I just installed fresh Vite react-ts project, Chakra, and tried putting a button on the page.
App.tsx:
```
import { Button } from '@chakra-ui/react';

function App() {
  return <Button colorScheme="blue">Button</Button>;
}

export default App;
```
TS error:
```
(property) ThemingProps<ThemeComponent extends string = any>.colorScheme?: (string & {}) | "blue" | "whiteAlpha" | "blackAlpha" | "gray" | "red" | "orange" | "yellow" | "green" | "teal" | "cyan" | "purple" | "pink" | "linkedin" | "facebook" | "messenger" | "whatsapp" | "twitter" | "telegram" | undefined
Expression produces a union type that is too complex to represent.ts(2590)
```

I've tried teling VSCode to use the workspace version which is 4.9.5

npm list:
```
├── @chakra-ui/react@2.5.3
├── @emotion/react@11.10.6
├── @emotion/styled@11.10.6
├── @types/node@18.15.10
├── @types/react-dom@18.0.11
├── @types/react@18.0.29
├── @vitejs/plugin-react@3.1.0
├── framer-motion@10.9.1
├── react-dom@18.2.0
├── react@18.2.0
├── typescript@4.9.5
└── vite@4.2.1
```

Any other ideas?

**Comment by scole954387** [comment]
> npm upgrade typescript@4.9.5

This doesn't work. I get "Update arguments must not contain package version specifiers"

**Comment by amneeshsoftobiz** [comment]
> 

it worked for me too.

**Comment by isimmons** [comment]
@scole954387  yeah I got the same error. I don't see anywhere in the npm cli docs that upgrade(update) is supposed to work that way. Also took a minute to find because its just an alias for update so you can't actually find any docs for an upgrade command.

I either manually change the version in my package.json and then run npm install or I use 2 commands to do it from the cli

npm remove typescript

npm install typescript@4.9.5

**Comment by thimholanda** [comment]
> # Solution
> 1. Open a JavaScript or TypeScript file in VS Code.
> 2. In the VS Code command palette, run the TypeScript: Select TypeScript version command.
> 3. Make sure you have `Use workspace version` selected
> 
> UPD: I have created a [question+answer](https://stackoverflow.com/questions/74847053/how-to-fix-expression-produces-a-union-type-that-is-too-complex-to-represent-t) on stackoverflow. I hope it helps someone :)

You saved my life!

**Comment by diwosuwanto** [comment]
> # Solution
> 1. Open a JavaScript or TypeScript file in VS Code.
> 2. In the VS Code command palette, run the TypeScript: Select TypeScript version command.
> 3. Make sure you have `Use workspace version` selected
> 
> UPD: I have created a [question+answer](https://stackoverflow.com/questions/74847053/how-to-fix-expression-produces-a-union-type-that-is-too-complex-to-represent-t) on stackoverflow. I hope it helps someone :)

This works, thanks!

**Comment by gabriel-caixeta** [comment]
> The fact that this is also happening in Vercel points to some incompatibility with TS and Chakra-ui (v2.5.2)

As mentioned above, this is also happening in Vercel, which shows that Chakra-UI is not compatible with TS `5.*`. I believe this issue needs to be reopened and looked into.

**Comment by tylerbecks** [comment]
You can also pin `chakra-ui/react` to `2.3.6`, something was introduced in a minor version between `2.3.6` and `2.5.5` that breaks even on typescript versions before typescript `5.x.x`

```json
"@chakra-ui/react": "2.3.6",
```

**Comment by cejaramillof** [comment]
> You can also pin `@chakra-ui/react` to `2.3.6`, something was introduced in a minor version between `2.3.6` and `2.5.5` that breaks even on typescript versions before typescript `5.x.x`
> 
> ```json
> "@chakra-ui/react": "2.3.6",
> ```
Thanks, it was the only thing that worked for me, because neither the `4.9.5` or `4.9.3` version of ts worked for me.

**Comment by mcreenan** [comment]
Can we get this re-opened, please?

I tested all versions from 2.3.6 to 2.5.5 and here are the results I got.  I am using a mono-repo with Nx and on TypeScript v5.0.4.

| @chakra-ui/react version | No error? |
|--------|--------|
| 2.3.6 | Success! |
| 2.3.7 | Success! |
| 2.4.0 | Success! |
| 2.4.1 | Success! |
| 2.4.2 | Success! |
| 2.4.3 | Success! |
| 2.4.4 | Success! |
| 2.4.5 | Failed! |
| 2.4.6 | Failed! |
| 2.4.7 | Failed! |
| 2.4.8 | Failed! |
| 2.4.9 | Failed! |
| 2.5.0 | Failed! |
| 2.5.1 | Failed! |
| 2.5.2 | Failed! |
| 2.5.3 | Failed! |
| 2.5.4 | Failed! |
| 2.5.5 | Failed! |

So it seems this started happening in v2.4.5.

Here's the script I used to test:

```bash
#!/bin/bash

for v in 2.3.6 2.3.7 2.4.0 2.4.1 2.4.2 2.4.3 2.4.4 2.4.5 2.4.6 2.4.7 2.4.8 2.4.9 2.5.0 2.5.1 2.5.2 2.5.3 2.5.4 2.5.5; do
  echo -n "Testing $v... "
  rm -rf node_modules >> test-chakra-ui.log 2>&1;
  yarn >> test-chakra-ui.log 2>&1;
  yarn upgrade @chakra-ui/react@$v >> test-chakra-ui.log 2>&1;
  if yarn nx build <project_name> --skip-nx-cache >> test-chakra-ui.log 2>&1; then
    echo "Success!"
  else
    echo "Failed!"
  fi
done
```

**Comment by akd-io** [comment]
Thanks a lot, @mcreenan, I hope they reopen. I've pinned my `@chakra-ui/react` version to `2.4.4` till further notice.

**Comment by RobinClowers** [comment]
FYI, there is a new issue that tracks this specific for Typescript 5.0: https://github.com/chakra-ui/chakra-ui/issues/7526

**Comment by RedDotz20** [comment]
Just an update from mine:
I updated `@chakra-ui/react` to version `2.6.0` and my `typescript` version from version `4.9.5` to `5.0.4`.
seems to be working fine as of now... I guess

Previous version I'm using (stable for me):
```json
"@chakra-ui/react": "~2.5.5",
"typescript": "~4.9.5"
```

Latest version I'm using (works for me):
```json
"@chakra-ui/react": "~2.6.0",
"typescript": "~5.0.4"
```

**Comment by Inviz** [comment]
I can confirm latest @chakra-ui/react fixes it. thanks

**Comment by mcreenan** [comment]
Unfortunately, 2.6.0 (with TypeScript 5.0.4) does _not_ fix the issue for me. 

My results using my script:
| `@chakra-ui/react` version | Status |
|--------|--------|
| 2.4.4 | Success |
| 2.4.5 | Failed |
| 2.6.0 | Failed |

**Comment by JakeGinnivan** [comment]
Can you ensure you don't have duplicate chakra packages in your lockfile? 

When I upgraded I ended up with some of the packages duplicated so i had multiple versions of some packages. I had to manually sort out then things came good.

**Comment by alexdanilowicz** [comment]
## Update May 2023

Thank you to all of those who helped. Simply upgrade your versions to the latest.

I no longer experience the problem on:

-  `"@chakra-ui/react": "^2.6.0"`
-  `"typescript": "^5.0.4"`

For reference: using nextjs 13.0.7 and node v18.12.1

**Comment by mcreenan** [comment]
For anyone else that finds this issue:

https://github.com/chakra-ui/chakra-ui/issues/7526#issuecomment-1639639156

Following the recommendation from this comment looks like it fixes the issue.
