### ISSUE TITLE
`TypeError: (0 , import_styled_system4.defineCssVars) is not a function` due to outdated dependency on @chakra-ui/styled-system

### ISSUE THREAD

**Issue by felixfbecker** [chakra-ui/chakra-ui#7523]
### Description

When running `chakra-cli tokens theme.cts` with a theme.cts file that uses `@chakra-ui/pro-theme` and `extendTheme()` like:

```ts
import { theme as proTheme } from "@chakra-ui/pro-theme"
import { extendTheme, withDefaultColorScheme } from "@chakra-ui/react"

export const theme = extendTheme(
  {
    styles: { /* ... */ },
  }
  withDefaultColorScheme({ /* ... */ }),
  proTheme
)
```

it fails with 
```
TypeError: (0 , import_styled_system4.defineCssVars) is not a function
    at Object.<anonymous> (node_modules/@chakra-ui/theme/dist/index.js:362:52)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (node_modules/@chakra-ui/theme-utils/dist/index.js:40:20)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
```

This seems to be because `@chakra-ui/theme` uses `defineCssVars()` from `@chakra-ui/styled-system@2.8.0`, but actually only defines a `peerDependency` constraint for `@chakra-ui/styled-system@>=2.0.0`. Since `@chakra-ui/pro-theme` still has an _exact_ dependency on `@chakra-ui/styled-system@2.5.1`, NPM will always dedupe the package so that all version constraints are satisfied, meaning it will install `2.5.1` for `@chakra-ui/theme`, which should be valid according to its constraints. But it then uses an API that only exists in 2.8.0, causing the runtime error.

I think the correct thing would be to update the peerDependency to `2.8.0` given it does not work with `>=2.0.0` anymore as currently stated.

Additionally it would be nice to update `@chakra-ui/pro-theme` to use the latest version of `@chakra-ui/styled-system`.

### Link to Reproduction

Since this is a problem with the CLI, I don't think I can repro this in CodeSandbox

### Steps to reproduce

See description above

### Chakra UI Version

2.5.5

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by cschroeter** [comment]
Resolved in https://github.com/chakra-ui/chakra-ui/commit/c2f0d1bb2a07fe6af5e53a1f216d80c9a7d6df72
