### ISSUE TITLE
stylis.middleware is not a function during testing. 

### ISSUE THREAD

**Issue by tomsonpl** [chakra-ui/chakra-ui#2560]
# Bug report

Tests fail because of emotions 11 stylis issue.

## Describe the bug

After updating to v1, we started having this `stylis.middleware is not a function` error on tests. After quick googling it appeared to be stylis and emotion issue. 

https://github.com/emotion-js/emotion/issues/2103 

Are you planning to bump the version after they release the fix (is ready apparently)? Or you want to fix it somehow? 

Cheers!

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies): [e.g. Chrome, Safari]
- Version of @chakra-ui/react: [e.g. 1.0.0-rc.3]
- Version of Node.js: [e.g. 12.11.1]

**Comment by ljosberinn** [comment]
This seems to be unrelated to Chakra. The newest Emotion version does not contain any reference to the issue and Andarist is I believe referencing create-react-app or stylis when saying "with the new release".
